"""Renders Confluence storage-format (XHTML-ish) page bodies for the
per-model documentation pipeline. No LLM code, no network -- pure string
building. All dynamic text is HTML-escaped.

Each rendered page is explicit about provenance: the structure block is
labelled as coming from dbt's manifest.json / catalog.json, and the logic
summary is labelled as LLM-generated -- so a reader never has to guess which
half is authoritative.
"""

from __future__ import annotations

import html

from model_docs.models import ModelLogicSummary, ModelStructure, ServeField

MODEL_PAGE_PREFIX = "dbt model: "
SERVE_OVERVIEW_TITLE = "Serve Layer Overview"


def model_page_title(model_name: str) -> str:
    return f"{MODEL_PAGE_PREFIX}{model_name}"


def _e(text: object) -> str:
    return html.escape(str(text))


def _ul(items: list[str]) -> str:
    if not items:
        return "<p><em>(none)</em></p>"
    return "<ul>" + "".join(f"<li>{_e(item)}</li>" for item in items) + "</ul>"


def _panel(text: str) -> str:
    """A Confluence 'info' macro -- renders as a callout box."""
    return (
        '<ac:structured-macro ac:name="info">'
        f"<ac:rich-text-body><p>{_e(text)}</p></ac:rich-text-body>"
        "</ac:structured-macro>"
    )


def render_model_page(structure: ModelStructure, summary: ModelLogicSummary) -> str:
    columns_note = (
        "Columns and data types are read from dbt's catalog.json "
        "(warehouse-observed, complete)."
        if structure.columns_from_catalog
        else "catalog.json was unavailable -- only the columns documented in "
        "schema.yml are listed, so this may be incomplete."
    )

    rows = "".join(
        f"<tr><td>{_e(col.name)}</td><td>{_e(col.data_type)}</td></tr>"
        for col in structure.columns
    )
    columns_table = (
        "<table><tbody>"
        "<tr><th>Field</th><th>Data type</th></tr>"
        f"{rows}"
        "</tbody></table>"
        if structure.columns
        else "<p><em>(no columns found)</em></p>"
    )

    return "".join(
        [
            _panel(
                "Structure below (layer, source tables, referenced models, fields) "
                "is generated deterministically from dbt's manifest.json + catalog.json. "
                "The business-logic summary is generated by an LLM from the compiled SQL "
                "and is descriptive, not authoritative."
            ),
            f"<p><strong>Model:</strong> {_e(structure.name)} "
            f"(<code>{_e(structure.layer)}</code> layer)<br/>"
            f"<strong>Path:</strong> <code>dbt_project/models/{_e(structure.relative_path)}</code><br/>"
            f"<strong>Schema:</strong> <code>{_e(structure.schema_name)}</code></p>",
            "<h2>Source tables</h2>",
            _ul(structure.source_tables),
            "<h2>Referenced models</h2>",
            _ul(structure.referenced_models),
            "<h2>Fields selected</h2>",
            f"<p><em>{_e(columns_note)}</em></p>",
            columns_table,
            "<h2>Business logic (LLM-generated)</h2>",
            f"<p>{_e(summary.summary)}</p>",
            "<h3>Key transformations</h3>",
            _ul(summary.key_transformations),
        ]
    )


def render_serve_overview_page(fields: list[ServeField]) -> str:
    rows = "".join(
        "<tr>"
        f"<td>{_e(f.model)}</td>"
        f"<td>{_e(f.field)}</td>"
        f"<td>{_e(f.data_type)}</td>"
        f"<td>{_e(f.description) if f.description else ''}</td>"
        "</tr>"
        for f in fields
    )
    body = (
        "<table><tbody>"
        "<tr><th>Serve model</th><th>Business-friendly field</th><th>Data type</th><th>Description</th></tr>"
        f"{rows}"
        "</tbody></table>"
        if fields
        else "<p><em>(no serve_ model fields found)</em></p>"
    )
    return "".join(
        [
            _panel(
                "This data dictionary is generated deterministically from the serve_ "
                "models' column names and catalog.json data types. The serve layer is "
                "rename-only (see CLAUDE.md), so these column names are the "
                "business-friendly names -- no LLM is involved."
            ),
            "<h2>Fields across all serve_ models</h2>",
            body,
        ]
    )
