-- mock_erp schema: synthetic SAP-style sales order data.
--
-- Modeled loosely on SAP's VBAK (sales document header) / VBAP (sales
-- document item) tables. Kept to plain ANSI types (INTEGER, VARCHAR, DATE,
-- DECIMAL) with no engine-specific syntax (no SERIAL/IDENTITY/SEQUENCE) so
-- this runs unmodified against DuckDB or Postgres -- whichever a given
-- connector points at.
--
-- IDs are generated by the caller (see seed_data.py), not by the database,
-- which is what keeps this file portable across engines.

CREATE TABLE IF NOT EXISTS vbak (
    order_id    INTEGER      NOT NULL,  -- VBELN: sales order number
    customer_id VARCHAR(10)  NOT NULL,  -- KUNNR: sold-to customer
    order_date  DATE         NOT NULL,  -- ERDAT: order creation date
    status      VARCHAR(20)  NOT NULL,  -- one of: completed, in_process, cancelled, incomplete
    PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS vbap (
    order_id    INTEGER        NOT NULL,  -- VBELN: FK to vbak.order_id
    item_id     INTEGER        NOT NULL,  -- POSNR: line item number within the order
    material_id VARCHAR(10)    NOT NULL,  -- MATNR: material/product number
    quantity    INTEGER        NOT NULL,  -- KWMENG: order quantity
    net_value   DECIMAL(15, 2) NOT NULL,  -- NETWR: net value of the line item
    PRIMARY KEY (order_id, item_id),
    FOREIGN KEY (order_id) REFERENCES vbak (order_id)
);
